danielroe/nuxt-vitest

- package.json
- pnpm-lock.yaml
- src/config.ts
So we could use it programically and feed the existing nuxt instance instead of creating a new one.
> feat(getVitestConfig): pass custom nuxt instance and config to `getVitestConfig`

- src/runtime/mount.ts
In some scenarios, `Suspense` seems to be resolved synchronously, causing this error:
> fix: wait a tick for `mountSuspended`

- packages/vitest-environment-nuxt/src/runtime/components/RouterLink.ts
Trying to fix an error I've got when using `mountSuspended` with a component that had a `NuxtLink`:
```
ReferenceError: h is not defined
```
Related: https://github.com/danielroe/vitest-environment-nuxt/pull/24
<details>
<summary>ℹ️ More info ⬇️</summary>
The problem is that when the library gets compiled, the `h` gets renamed:
It's correctly used in the other module that consumes it:
But not in the `RouterLink` component:
(all screenshots are in the same file, `/dist/utils.mjs`.)
</details>
> fix: import explicitly h

- packages/vitest-environment-nuxt/src/runtime/components/RouterLink.ts
The vue-router mock doesn't accept a named route object.
```
[Vue warn]: Invalid prop: type check failed for prop "to". Expected String with value "[object Object]", got Object  
```
> fix: accept object syntax for `to` prop in router mock

- packages/nuxt-vitest/src/config.ts
`InlineConfig` is imported twice in [config.ts](https://github.com/danielroe/nuxt-vitest/blob/main/packages/nuxt-vitest/src/config.ts#L2), once from `vitest` and once from `vite`. To prevent a naming conflict, the `InlineConfig` from Vitest is aliased to `VitestConfig`.
However, `defineVitestConfig` [expects](https://github.com/danielroe/nuxt-vitest/blob/main/packages/nuxt-vitest/src/config.ts#L92) Vite's `InlineConfig` as a type, instead of the aliased `VitestConfig`.
This means TypeScript is unhappy when you pass a `test` object to `defineVitestConfig`. 
```
Argument of type '{ test: { clearMocks: boolean; environment: string; globals: boolean; }; }' is not assignable to parameter of type 'InlineConfig'.
Object literal may only specify known properties, and 'test' does not exist in type …
```
> fix: correct type of `defineVitestConfig`

- packages/vitest-environment-nuxt/src/modules/mock.ts
- playground/tests/nuxt/mock-nuxt-composable.spec.ts
The `mockNuxtImport` doesn't accept a core nuxt composable
```
Cannot find import "useRuntimeConfig" to mock
```
Refs: #29
> fix: mock core nuxt composables

- packages/nuxt-vitest/src/config.ts
Reverts danielroe/nuxt-vitest#72
Closes https://github.com/danielroe/nuxt-vitest/issues/85
This pull request reverts the earlier pull request, in which I attempted to resolve a typing issue in `defineVitestConfig`. My apologies for causing this regression problem 😢!
I've done some more digging, and I was initially under the impression that the `UserConfig` type did not contain a `test?` property. However, Vitest does extend `UserConfig` with a `test?` property [here](https://github.com/vitest-dev/vitest/blob/c44e5afe135c804ee224bcfa0c5b70ebe47187f4/packages/vitest/src/types/vite.ts#L10).
This did not work in my project however, as my `yarn.lock` contained two `vite` listings due to a versioning conflict between Nuxt's requested Vite version uses and the requested Vite version of the …
> fix: revert type change to `defineVitestConfig`

- packages/nuxt-vitest/src/config.ts
- packages/vitest-environment-nuxt/src/index.ts
- playground/nuxt.config.ts
- playground/tests/nuxt/config.spec.ts
Resolves danielroe/nuxt-vitest#29
> fix: pass resolved `runtimeConfig` into nuxt environment

- README.md
Hey 👋 
Here is some information on how to provide multiple implementations of a mocked Nuxt import, between tests.
Closes #65
> docs: add more info about `mockNuxtImport`

- packages/vitest-environment-nuxt/src/index.ts
While using testing libraries such as: 
https://testing-library.com/docs/vue-testing-library/intro/
And trying to get full [coverage](https://vitest.dev/guide/coverage.html) of the template while mounting a simple component using child components from:
https://headlessui.com/vue/menu
I encountered missing coverage in my testing; after trying different things, it seems some events are not properly propagated by vue-testing-library fireEvent method, so I tried to use an extension they developed for this situation:
https://github.com/testing-library/user-event
When executing my code using the library mentioned I was able to get full coverage, but I saw an error in my console
```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Vitest caught 1 unhandled error …
```
> fix: support `unobserve` method in mocked IntersectionObserver

- README.md
In order to inform early about incompatabilities and avoid [invalid bug reports](https://github.com/nuxt/nuxt/issues/20651#event-9164321110) we introduce a section specifically targeting the conflict with `@nuxt/test-utils`
> docs: add example `@nuxt/test-utils` config

- .gitignore
- packages/vitest-environment-nuxt/package.json
- packages/vitest-environment-nuxt/src/runtime/components/RouterLink.ts
- packages/vitest-environment-nuxt/src/runtime/mount.ts
- playground/components/OptionsComponent.vue
- playground/tests/nuxt/index.spec.ts
- pnpm-lock.yaml
This PR adds mount support for vue-test-utils mount function. (See https://github.com/danielroe/nuxt-vitest/issues/87)
Mostly of the work has been done by @ghazialhouwari. (https://github.com/ghazialhouwari/nuxt-vitest)
Tests haven't been tested cause of the following issue:
```
Cannot read properties of null (reading 'scope')
```
Looks like it's a SSR issue and the component is missing an active currentInstance, see https://github.com/vuejs/core/issues/7402 for more information.
See screenshot for Vue warnings:
> feat: allow passing mount options in `mountSuspended`

- README.md
The Setup Sections explains how to opt-in or set the nuxt-environment globally. 
There is good chance global nuxt environment for existing project causes error in some spec files so this introduces a follow up hint how to opt-out of the global env per test file. 
stackblitz: https://stackblitz.com/edit/nuxt-vitest-c8mrz7?file=vitest.config.mjs,test%2Fapp.e2e.spec.ts,tsconfig.json
> docs: add directions on opting out from global environment

- README.md
because the file example does not provide a named export 
```
// useStorageMock.ts
let useStorageMock = vi.fn(() => {
return { value: 'mocked storage' }
})
export default useStorageMock
```
> docs: correct import style for composable mock file example

- README.md
Added some info about `registerEndpoint` utility.
Related to #197.
> docs: add info about `registerEndpoint` utility

- README.md
The document missed the vitest dependency while installing, and the nuxt-vitest module dosen't expose vitest to user application by default, missing the vitest dependency may misleading users that they can use vitest directy from nuxt-vitest.
> docs: install `vitest` in installation guide

- packages/vitest-environment-nuxt/src/index.ts
- playground/nuxt.config.ts
- playground/tests/nuxt/index.spec.ts
This PR relates to #121 and fixes some underlying test issues uncovered when attempting to fix the failing tests in that PR.
---
By default `happy-dom` will have the URL `about:blank`. In the tests it seems we were assuming we would immediately end up on an index page when in fact we were not due to this behavior of `happy-dom`.
This change properly sets the default URL to `http://localhost:3000` which is the same as Vitest sets for JSDOM.
There were two tests that started failing for this change:
1. "defaults to index page" 
This test previously was ending up on the "slug" page, since the URL was matching "about:blank" to this. This snapshot was updated since it now correctly goes to the index page.
2. "allows pushing to other pages"
The `useRoute()` in this test can no longer be called …
> fix: properly set default route

- .github/workflows/ci.yml
- packages/vitest-environment-nuxt/package.json
- packages/vitest-environment-nuxt/src/index.ts
- pnpm-lock.yaml
See details and triage in https://github.com/danielroe/nuxt-vitest/issues/278
It seems we cannot access `globalThis.fetch` during environment setup (it's always `undefined`), and `JSDOM` in incompatible with `node-fetch` (and by extension `node-fetch-native`) meaning we have to use some other `fetch` polyfill for JSDOM.
Thus I've made the following changes:
- For JSDOM we will now use `whatwg-fetch` which seems to be standard compliant, and passes all of the tests.
- For Happy-DOM we will now use its own `fetch` implementation (which seems to be a forked and better version of node-fetch).
I also added a step to CI to actually run the unit tests with JSDOM now that they're passing.
> fix: improve fetch polyfill implementations

- README.md
Changed an example in the readme about using `mockNuxtImport`. 
If you want to have access to your mock in the test, the previous example encouraged to make a seperate file per mock to be able to expose it as global variable so it would be accessible in `mockNuxtImport`, as it was hoisted and otherwise not available.
Recently, `vitest` introduced `vi.hoisted`. Wit this, we can hoist code before any mocks are created, thus allowing for a much easier way to access mocks in our tests. I've updated the readme with an example of this. It replaces the current example where a seperate file is used.
> docs: include `vi.hoisted` as an example with `mockNuxtImport`

- packages/vitest-environment-nuxt/src/modules/mock.ts
- playground/composables/auto-import-mock.ts
- playground/nuxt.config.ts
- playground/tests/nuxt/auto-import-mock.spec.ts
- playground/tests/setup/mocks.ts
- playground/vitest.config.ts
Hi :wave: 
This PR allows mocking imports within setup files. 
Currently if we can only use `mockNuxtImport` either within the setup file or within the test file.
The idea behind this PR is to use the new `vi.hoisted` from vitest 0.31 to set globally a `__NUXT_VITEST_MOCKS` variable which would contains all imports (mocked or not).
`mockNuxtImport` will instead of returning the module modified, assign the module within the `__NUXT_VITEST_MOCKS` variable, modify the mocked import and return `__NUXT_VITEST_MOCKS`
> feat(vitest-environment-nuxt): allow mocking imports within setup files

- .npmrc
- package.json
Enable shell-emulator
Running `stub` script, we should also update it:
closes #225
> chore: fix tests on Windows

- packages/vitest-environment-nuxt/package.json
https://arethetypeswrong.github.io/?p=vitest-environment-nuxt%400.10.2
> fix: add node10 types for `vitest-environment-nuxt`

- README.md
- packages/vitest-environment-nuxt/package.json
- packages/vitest-environment-nuxt/src/runtime/render.ts
- packages/vitest-environment-nuxt/src/utils.ts
- playground/package.json
- playground/tests/nuxt/utils-render.spec.ts
- playground/vitest.config.ts
- pnpm-lock.yaml
Resolves https://github.com/danielroe/nuxt-vitest/issues/271
This PR adds a new utility function: `renderSuspended`. This works similarly to `mountSuspended` but instead of @vue/test-utils uses @testing-library/vue and its `render` function.
The implementation is almost a duplicate of `mountSuspended` with the difference being that we wrap the root element in a div. This is necessary for `@testing-library/vue` to be able to render `Suspended`.
*TODOs*
*Open questions*
- Should this add `@testing-library/vue` as an optional peer dependency or a mandatory one?
> feat: add `renderSuspended` for use with testing-library

- packages/vitest-environment-nuxt/src/runtime/render.ts
Hi :wave: 
This PR resolves #330 , this removes the import from `@testing-library/vue` in the final build of the utils file
> fix(vitest-environment-nuxt): import `@testing-library/vue` within `renderSuspended`

- packages/vitest-environment-nuxt/src/runtime/mock.ts
- playground/tests/nuxt/index.spec.ts
This PR lets you specify an optional HTTP method for a given endpoint so that one can mock different responses/behavior depending on said method.
> feat(utils): add method option to `registerEndpoint`

- packages/vitest-environment-nuxt/src/index.ts
Hi 👋
This PR resolves https://github.com/danielroe/nuxt-vitest/issues/370
> fix: respect custom `buildAssetsDir` when mocking manifests

- README.md
Changed `vitest.config.mjs` to `vitest.config.ts` to be more in line with other Nuxt documentation consistency and reduce confusion.
In the official [Nuxt: Getting Started Configuration](https://nuxt.com/docs/getting-started/configuration), it instructs the usage of a `vitest.config.ts` file. Furthermore, [Vitest: Configuration](https://vitest.dev/config/) also outlines the use of a `vitest.config.ts` file.
> docs: update to vitest config with `.ts` extension

- README.md
- packages/nuxt-vitest/src/config.ts
- packages/vitest-environment-nuxt/package.json
- packages/vitest-environment-nuxt/src/index.ts
- playground/components/IndexedDbComponent.vue
- playground/nuxt.config.ts
- playground/package.json
- playground/plugins/indexeddb.ts
- playground/tests/nuxt/mock-indexeddb.spec.ts
- playground/vitest.config.ts
- pnpm-lock.yaml
This will add some options for enabling some built-in mocks in nuxt-vitest. As for now I have added `intersectionObserver` (existing mock), and `indexedDB` (new mock).
I don't know if this is the best solution, but it is a start 😄
Ref. #287
> feat: allow `indexedDB` mock + disabling `IntersectionObserver`
